buildNumber: ${buildNumber}
buildTime: ${buildTime}
gitRevision: ${gitRevision}
gitBranch: ${gitBranch}

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ecommerce_product_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  file: /var/log/ecommerce-product-backend/product-prod.log
