buildNumber: unknown
buildTime: unknown
gitRevision: unknown
gitBranch: unknown

spring:
  datasource:
    url: jdbc:mysql://localhost:13307/ecommerce_product_mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: rabbitmq-user
    password: rabbitmq-password


ecommerce:
  rabbit:
    publishX: product-publish-x
    publishDlx: product-publish-dlx
    publishDlq: product-publish-dlq
    receiveQ: product-receive-q
    receiveDlx: product-receive-dlx
    receiveDlq: product-receive-dlq
    receiveRecoverX: product-receive-recover-x